name: 'Run rubocop with reviewdog'
description: '🐶 Run rubocop with reviewdog on pull requests to improve code review experience.'
author: 'mgrachev (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  rubocop_flags:
    description: 'rubocop flags. (rubocop <rubocop_flags>)'
    default: ''
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'rubocop'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  rubocop_version:
    description: 'Rubocop version'
    required: false
  rubocop_rails_version:
    description: 'Rubocop rails version'
    required: false
  rubocop_performance_version:
    description: 'Rubocop performance version'
    required: false
  rubocop_rspec_version:
    description: 'Rubocop rspec version'
    required: false
  rubocop_i18n_version:
    description: 'Rubocop i18n version'
    required: false
  rubocop_rake_version:
    description: 'Rubocop rake version'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.rubocop_flags }}
    - ${{ inputs.tool_name }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - ${{ inputs.rubocop_version }}
    - ${{ inputs.rubocop_rails_version }}
    - ${{ inputs.rubocop_performance_version }}
    - ${{ inputs.rubocop_rspec_version }}
    - ${{ inputs.rubocop_i18n_version }}
    - ${{ inputs.rubocop_rake_version }}
branding:
  icon: 'check-circle'
  color: 'red'
